const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
const FILTER_PRODUCTS_FAILURE = "FILTER_PRODUCTS_FAILURE";
const FILTER_PRODUCTS_SUCCESS = "FILTER_PRODUCTS_SUCCESS";
const LOADING_STATE = "LOADING_STATE";
const SET_ACTIVE_LINK = "SET_ACTIVE_LINK";

export {
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_FAILURE,
    FILTER_PRODUCTS_SUCCESS,
    FILTER_PRODUCTS_FAILURE,
    LOADING_STATE,
    SET_ACTIVE_LINK
}